-- Generated by HyprMod

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "2560x1440@239.99Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "2560x1440@144.00Hz",
    position = "-2560x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "2560x1440@59.95Hz",
    position = "2560x0",
    scale = 1,
    cm = "srgb",
})
